### PR TITLE
fix: create assume role policy inline

### LINKED ISSUE #438: Race condition when using self managed deployment type
I'm hitting a race condition when using a self managed deployment. It looks like the stack set resource starts deploying before the IAM role is ready, resulting in the following error message:

```
Resource handler returned message: "Resource of type 'Stack set operation [133a0012-7a7e-4ca6-a253-622c36c8d8d8] was unexpectedly stopped or failed. status reason(s): [Account <REDACTED> should have 'AWSCloudFormationStackSetExecutionRole' role with trust relationship to Role '<REDACTED>-AdminRole38563C57-xWR5IEOHv72o'.]' with identifier '<REDACTED>StackSet0EB2B840:bebe8bba-591e-4dd4-a637-1d631421d4d8' did not stabilize."
```

If I pre-create the admin role and specify it in the StackSet resource, it deploys successfully. Note that it does expose another minor issue, where [a duplicate policy](https://github.com/cdklabs/cdk-stacksets/blob/main/src/stackset.ts#L621C18-L621C38) is always added to the role.

### PR DESCRIPTION
**Pull request by tabrezm**
Fixes #438 

This PR moves the assume role policy inline to avoid a race condition of the stack set resource deployment before the policy is attached. As a consequence, an existing admin role won't be modified with a potentially duplicate policy.

### CODE REVIEW

**Review by comcalvi — CHANGES_REQUESTED** [review]
Looks good, just please add or modify an integ test for this one.

**Comment by tabrezm** [comment]
> Looks good, just please add or modify an integ test for this one.

I think the existing integration tests are sufficient but the snapshot needs to be updated because this PR removes the duplicate policy that gets added to the admin role. Unfortunately I'm a bit stumped on how to make this change on my end. I tried to run `yarn integ:update` but I'm not sure what values to set for `INTEG_DEPLOYMENT_ACCOUNT` or `INTEG_TARGET_ACCOUNT`. If I use a personal account, won't the checked-in snapshot point to it?

Please advise, thanks!

**Comment by robertjan-b** [comment]
I'm running into this issue as well. I want to have a pre-provisioned Admin role (due to the race condition) for the StackSet, but it tries to attach a duplicate inline permission to the pre-provisioned Admin role. This occurs when deploying multiple self managed stacksets with this same Admin role. Please fix the issue.

**Comment by go-to-k** [comment]
+1

I too hope this issue is resolved.

**Comment by kaizencc** [comment]
#678 is the right thing to do here so im going to close this in favor of that.

**Pull request closed without merging**
